lobby: null
lobbyWorldBorderRadius: null
spawn: null

settings:
  lobbyTime: 10  # Duration of the lobby phase in seconds
  preparationTime: 30  # Preparation time duration in seconds
  gameDuration: 5  # Duration of the game in minutes
  endDuration: 15  # Duration of the end phase in seconds
  initialSeeker: ""  # UUID of the initial seeker, if specified

  initialRadius: 1000  # Starting radius of the world border
  finalRadius: 100  # Ending radius of the world border
  hidersBecomeSeekers: false  # Set if hiders become seekers when found
  worldBorderDamageAmount: 1.0  # Damage amount caused by the world border
  worldBorderDamageBuffer: 0.0  # Buffer zone around the world border before damage is applied
  ohko: true  # Enable or disable "One Hit Knockout" (instant defeat when hit)

  world: "%first_world_name%"  # Name of the world; will use the default world if left blank
  worldBorderCenter:
    x: 0.0  # Default X-coordinate for the world border center
    z: 0.0  # Default Z-coordinate for the world border center

# Text von ChatGPT :)
